version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      #TODO[localhost]
      EVENT_SECRET: 'local_secret'
      EVENT_ENDPOINT: 'http://host.docker.internal:3000/api/events'
      #TODO[localhost]
      ACTION_ENDPOINT: 'http://host.docker.internal:3000/api/actions'
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      #TODO[localhost]
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
      HASURA_GRAPHQL_ADMIN_SECRET: 'admin-secret'
      #TODO[auth0 config]
      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url": "https://hanja-demo.us.auth0.com/.well-known/jwks.json"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
volumes:
  db_data:
