version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      #TODO[localhost]
      EVENT_SECRET: "local_secret"
      WEBHOOK_EVENT_ENDPOINT: "${DOMAIN}/hasura/event"
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      #TODO[localhost]
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres"
      HASURA_GRAPHQL_ADMIN_SECRET: "admin-secret"
      #TODO[auth0 config]
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDETCCAfmgAwIBAgIJej5szkKwxA/MMA0GCSqGSIb3DQEBCwUAMCYxJDAiBgNV\nBAMTG2hlcm9rdW5leHRqc2F1dGgwLmF1dGgwLmNvbTAeFw0yMDAzMDkwNDE0MTVa\nFw0zMzExMTYwNDE0MTVaMCYxJDAiBgNVBAMTG2hlcm9rdW5leHRqc2F1dGgwLmF1\ndGgwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMcLKQn0csNe\nWdPLJu7BR/rXoGL5VuDhtm4kLQljJGgUbwL1HFrdWMB8bAkjmtLYrnGNHF4l0PE1\nI0Scf7l2Sl/mw8DVab/2a01IYI0AbqZUIWBvh2d4kb8GkLEmkl2whDJxRXeGWZeR\nxtPoE7cXfvc8QY/eaqaT1iG2KwuzsVIzuUaIB73T+PblwsHqs7OHX6bJFbZAXC02\nBVoLR+BVlPqr+tqffWFXXmV3i1rC7B4gyTpBJG+Mf3RJnadhKjnK/B8tbJ32oQvp\nFyyXj/BSlyxQovnjSUDMS4qH7hjl95UBRIfYkPiuRZ4BO+PsiqwtvLFNL243EUOR\nSF+40enXfgUCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU9akv\nhd290OQ/XTL7NfPnQgXr55MwDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUA\nA4IBAQCV8F2LzOoWV4pMOq1mdkQ6Bg/oqGFO72BWlIe9xzDuWD9gTSZzF7HWWXyQ\nYpXvODFB6BzJLvS+ku42BAz8AerifysTGv56hGLOLNu0/CH8YKzZFcJDaEkZ4EHS\n3EX6uOQrzaum3zncMJtOIZ/epFZDg++4ivtTlOhq2iDfXhxC/AJOdJZl9YVhn7df\nl/JO9DFgrsolKfnKEXS64wyytI+0KNVuGk+qi3Ayvnm1ITMmWhuH3K8oQvMMg+vJ\nV0bFvcMsADw+059wE3wSysnQx5tsviH9obBHVN/My5gW9+4erZEcP9/Kx8TD20tU\nPJ+KQ6ODDB8PVu6kaBTUnhQx7BhG\n-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
volumes:
  db_data:
